services:
  flet:
    build:
      context: ./flet/src
      dockerfile: ../docker/Dockerfile.devel
    environment:
      WDB_SOCKET_SERVER: wdb
    ports:
      - "5000:5000"
    volumes:
      - ./flet/src:/opt/flet
    command: flet run --host * --port 5000 --web --verbose
  backend:
    build:
      context: ./flet/src
      dockerfile: ../docker/Dockerfile.devel
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./flet/src:/opt/flet
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload
  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"